### ISSUE TITLE
grpc-gateway calls golang/protobuf/jsonpb

### ISSUE THREAD

**Issue by mwitkow** [gogo/protobuf#178] opened 2016-05-13 08:45 UTC
This particular bug bit us:

To properly serialize/deserailize enums in `jsonpb` you need to call RegisterEnum. `gogo/protobuf`-generated messages register with `gogo/protobuf/properties.go`. However, if you have a library that is not under your control (e.g. gRPC Gateway), it will be using standard `golang/jsonpb` and thus the `golang/protobuf/properties` registration. Thus, any library using `golang/jsonpb` will not know about enums field maps.

Can we have a fix for this? Proposals include:
- having `gogo` register by only  with `golang/protobuf`
- having `gogo` register with both, or passing it up.

**Comment by mwitkow** [comment] 2016-05-13 08:54
This is a bit of sed that helps:
```
  # import upstream golang/protobuf as well
  sed -i -E 's~import proto "github.com/gogo/protobuf/proto"~\0\nimport golang_proto "github.com/golang/protobuf/proto~' ${GO_FILE_FULL}
  # Double up all registrations to golang_protobuf
  sed -i -E 's~^([[:space:]]*)proto.Register(.*)$~\0\n\1golang_proto.Register\2~' ${GO_FILE_FULL}
```

**Comment by awalterschulze** [comment] 2016-05-13 09:30
Damn that sucks :(
I'll have to think about this more.

I do have an extension that imports golang/protobuf instead of gogo/protobuf, maybe that can help?
This is what protoc-gen-gofast uses.

**Comment by tamird** [comment] 2016-05-16 19:48
I'm not sure this is a "real" issue - truth is that using `golang/protobuf/jsonpb` to serialize/deserialize protos generated by gogo/protobuf doesn't work reliably (e.g. it doesn't support non-nullable non-scalar fields), so you really want to use `gogo/protobuf/jsonpb`.

The workaround isn't so bad, see my solution in https://github.com/cockroachdb/cockroach/pull/6587/commits/2101119350ceaaba60e150f9e5fd3355acd9fefc

**Comment by awalterschulze** [comment] 2016-05-16 19:53
Ok maybe it just bothers me :-)

**Comment by mwitkow** [comment] 2016-05-16 20:19
Tamir, agreed. However if your vendored dependency used
golang/protobuf/jsonpb you're in very much of a pickle.

I think that having golang/protobuf generate MarshalJSON functions that use
jsonpb would be the best solution to the problem.

**Comment by awalterschulze** [comment] 2016-05-16 20:24
Sorry I replied to wrong issue

**Comment by awalterschulze** [comment] 2016-05-17 05:32
Line 58 of jsonpb_marshaler should probably be jsonpb.Unmarshal not
proto.Unmarshal

**Comment by awalterschulze** [comment] 2016-05-17 08:04
I also think the generated MarshalJSON functions will solve all a lot of problems.

**Comment by awalterschulze** [comment] 2016-09-10 08:26
Maybe we should make an issue with grpc-gateway to allow us to inject our own jsonpb marshaler codec, just like grpc-go allows you to inject a codec interface?

**Comment by mwitkow** [comment] 2016-09-12 07:48
gRPC gateway already allows one to do that. It's just confusing as hell. 

I actually think that double registration would be the better solution here.

**Comment by awalterschulze** [comment] 2016-09-12 16:58
How is it confusing, maybe you can explain more?  Worst case for someone else finding this issue.

**Comment by mwitkow** [comment] 2016-09-12 19:11
For example: you use the default grpc gateway codes and gogo as your proto
compiler. Unknowingly you pass your messages to grpc gateway. Your enums
are not registered and serialised as ints and you can parse valid proto3 in
json format.

**Comment by awalterschulze** [comment] 2016-09-12 19:15
Ok so everything works in that case?

**Comment by tamird** [comment] 2016-09-12 22:56
For reference: https://github.com/cockroachdb/cockroach/blob/develop/util/jsonpb_marshal.go

**Comment by awalterschulze** [comment] 2016-09-13 05:58
Wow that is a lot of quite complex code, but as you said there are other issues with using golang/protobuf/jsonpb with gogoprotobuf generated structures, like non-nullable non-scalar fields.  Have you brought this up with grpc-gateway.  I would think that there would be an easier interface to implement.

**Comment by tamird** [comment] 2016-09-17 12:28
I haven't, but it's probably worthwhile to do so.

Having to copy `marshalNonProtoField` is really unfortunate.

**Comment by awalterschulze** [comment] 2016-09-19 17:17
Whoever opens this issue could CC me in on the issue.  I would like to at least follow.

**Comment by awalterschulze** [comment] 2016-10-18 15:45
Doesn't seem like the issue was ever opened https://github.com/gogo/protobuf/issues/212#issuecomment-253883168

**Comment by johanbrandhorst** [comment] 2016-10-28 09:48
We're currently getting a `proto: no coders for int` message printed on `STDERR` when returning `grpc.Code`s over grpc-gateway, is that because of this? We vendored @tamird's workaround and everything else works, but are still seeing those messages. Could someone with a better understanding explain what's going on an preferably raise that issue?

**Comment by awalterschulze** [comment] 2016-10-29 07:41
I would report this issue if I was using grpc-gateway, but unfortunately I am not.  Also I don't perfectly understand.  I am guessing.  I would suggest putting in a panic at the place this warning it being printed out to find out how this call is happening.  And then report this issue.

**Comment by johanbrandhorst** [comment] 2016-10-31 12:25
Sounds reasonable, I'll give it a go

**Comment by johanbrandhorst** [comment] 2016-11-01 11:29
For reference, I've managed to get a panic traceback, just posting it here before raising it against grpc-gateway:

```go
2016/11/01 11:22:15 http2: panic serving 127.0.0.1:49722: proto: no coders for int
goroutine 427 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc4201381c0, 0xc4201e7f5f, 0xc420378b40)
	/usr/local/go/src/net/http/h2_bundle.go:4304 +0xd1
panic(0x8ac880, 0xc4202a6770)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/johanbrandhorst/myrepo/vendor/github.com/gogo/protobuf/proto.(*Properties).setEncAndDec(0xc42008ef20, 0xbfd8e0, 0x8ac140, 0xc4201e6eb0, 0x1)
	~/myrepo/vendor/github.com/gogo/protobuf/proto/properties.go:381 +0x382
github.com/johanbrandhorst/myrepo/vendor/github.com/gogo/protobuf/proto.(*Properties).init(0xc42008ef20, 0xbfd8e0, 0x8ac140, 0x88a710, 0x4, 0x88a720, 0x11, 0xc4201e6eb0, 0xc42008ef01)
	~/myrepo/vendor/github.com/gogo/protobuf/proto/properties.go:713 +0xcb
github.com/johanbrandhorst/myrepo/vendor/github.com/gogo/protobuf/proto.(*Properties).Init(0xc42008ef20, 0xbfd8e0, 0x8ac140, 0x88a710, 0x4, 0x88a720, 0x11, 0xc4201e6eb0)
	~/myrepo/vendor/github.com/gogo/protobuf/proto/properties.go:699 +0x7f
github.com/johanbrandhorst/myrepo/vendor/github.com/gogo/protobuf/jsonpb.jsonProperties(0x88a710, 0x4, 0x0, 0x0, 0xbfd8e0, 0x8ac140, 0x88a716, 0x28, 0x10, 0xc4202a65a8, ...)
	~/myrepo/vendor/github.com/gogo/protobuf/jsonpb/jsonpb.go:892 +0xe1
github.com/johanbrandhorst/myrepo/vendor/github.com/gogo/protobuf/jsonpb.(*Marshaler).marshalObject(0xc4202ccf80, 0xc4201e7518, 0x7f9012377670, 0xc4202ae2e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4202ec000)
	~/myrepo/vendor/github.com/gogo/protobuf/jsonpb/jsonpb.go:222 +0x406
github.com/johanbrandhorst/myrepo/vendor/github.com/gogo/protobuf/jsonpb.(*Marshaler).Marshal(0xc4202ccf80, 0xbeecc0, 0xc420308380, 0x7f9012377670, 0xc4202ae2e0, 0x1, 0xc420308380)
	~/myrepo/vendor/github.com/gogo/protobuf/jsonpb/jsonpb.go:79 +0xca
github.com/johanbrandhorst/myrepo/vendor/github.com/gogo/protobuf/jsonpb.(*Marshaler).Marshal-fm(0xbeecc0, 0xc420308380, 0x7f9012377670, 0xc4202ae2e0, 0x8f9501, 0xc4202a62c0)
	~/myrepo/vendor/github.com/cockroachdb/cockroach/pkg/util/httputil/http.go:71 +0x52
github.com/johanbrandhorst/myrepo/vendor/github.com/cockroachdb/cockroach/pkg/util/protoutil.(*JSONPb).marshal(0xc4202ccf80, 0x8e4580, 0xc4202ae2e0, 0x411a68, 0x20, 0x8f9540, 0x96a701, 0xc4202ae2e0)
	~/myrepo/vendor/github.com/cockroachdb/cockroach/pkg/util/protoutil/jsonpb_marshal.go:57 +0x118
github.com/johanbrandhorst/myrepo/vendor/github.com/cockroachdb/cockroach/pkg/util/protoutil.(*JSONPb).Marshal(0xc4202ccf80, 0x8e4580, 0xc4202ae2e0, 0x35, 0x10, 0x8ed040, 0xbf75c0, 0xc4202ac720)
	~/myrepo/vendor/github.com/cockroachdb/cockroach/pkg/util/protoutil/jsonpb_marshal.go:48 +0x3f
github.com/johanbrandhorst/myrepo/vendor/github.com/grpc-ecosystem/grpc-gateway/runtime.DefaultHTTPError(0x7f90123337c0, 0xc4202ac720, 0xbf89a0, 0xc4202ccf80, 0xbf6b00, 0xc4201381c0, 0xc42037e960, 0xbef700, 0xc4202ae2c0)
	~/myrepo/vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go:91 +0x1cf
net/http.(*ServeMux).ServeHTTP(0xc420243680, 0xbf6b00, 0xc4201381c0, 0xc42037e960)
    /usr/local/go/src/net/http/server.go:2022 +0x7f
....
<my code>
....
created by net/http.(*http2serverConn).processHeaders
    /usr/local/go/src/net/http/h2_bundle.go:4092 +0x6e2
```

**Comment by johanbrandhorst** [comment] 2016-11-01 11:34
On second thought, I'd love to have some input from @tamird and @mwitkow about the precise cause of the problem here so I can make an educated issue against grpc-gateway. Any chance you could elaborate a little bit?

**Comment by awalterschulze** [comment] 2016-11-01 12:37
Wow ok that trace is very interesting.
Could you also print out f *reflect.StructField

**Comment by johanbrandhorst** [comment] 2016-11-01 12:49
```
2016/11/01 12:48:56 http2: panic serving 127.0.0.1:52008: proto: no coders for Kind: int, StructField: &{Code  int protobuf:"bytes,2,name=code" json:"code" 16 [1] fals
e}
```

**Comment by awalterschulze** [comment] 2016-11-01 12:52
Where is it finding this `int` field?

**Comment by johanbrandhorst** [comment] 2016-11-01 12:59
Using the debugger, I get this value for the `valueField` on ln 177 in gogo/protobuf/jsonpb/jsonpb.go:

```go
valueField
<reflect.StructField>
Name:"Code"
PkgPath:""
Type:<reflect.Type>
Tag:"protobuf:"bytes,2,name=code" json:"code""
Offset:16
Index:<[]int> (length: 1, cap: 1)
Anonymous:false
```

**Comment by awalterschulze** [comment] 2016-11-01 13:45
Ok I'm stump.  Where is this Code field coming from?

**Comment by johanbrandhorst** [comment] 2016-11-01 14:07
It's a gRPC [codes.Code](https://godoc.org/google.golang.org/grpc/codes#Code).

**Comment by awalterschulze** [comment] 2016-11-01 14:11
That is a `uint32` and not an `int`

**Comment by johanbrandhorst** [comment] 2016-11-01 14:17
Ah yes, sorry, it's actually from grpc-gateway/runtime/errors.go:

```go
type errorBody struct {
	Error string `protobuf:"bytes,1,name=error" json:"error"`
	Code  int    `protobuf:"bytes,2,name=code" json:"code"`
}
```

**Comment by awalterschulze** [comment] 2016-11-01 14:20
This looks like a hack.

**Comment by johanbrandhorst** [comment] 2016-11-01 14:22
I suppose it's meant to just marshal the int to a JSON integer without asking any questions? If there is an issue here against grpc-gateway I'll gladly raise it.

**Comment by awalterschulze** [comment] 2016-11-01 14:29
I wonder how golang/protobuf does not have the same problem.
Is it possibly because of this protoutil that only gogoprotobuf has this issue?

I still think they just make the int an int64 to make it a proper protobuf and this might be a raisable issue?

**Comment by johanbrandhorst** [comment] 2016-11-01 14:58
I'd love for @tarmid and @mwitkow to weigh in on this as I'm not sure exactly what causes the problem.

**Comment by johanbrandhorst** [comment] 2016-11-02 09:32
I can reproduce the same problem using `golang/protobuf/jsonpb` as the grpc-gateway marshaler, so not sure where the error is coming from now.

**Comment by awalterschulze** [comment] 2016-11-02 10:07
Well seems like it should now be easy to report to grpc-gateway or not?

**Comment by johanbrandhorst** [comment] 2016-11-02 14:51
I'm still not sure this isn't somehow related to the use of gogo/protobuf generated protofiles, I'd like to just get a minimal sample project up and play around with it.

**Comment by awalterschulze** [comment] 2016-11-03 06:47
Sounds like a good plan.

**Comment by tamird** [comment] 2016-11-06 21:39
@johanbrandhorst it seems that this log manifests exactly whenever grpc-gateway is used to return an error from a grpc handler.

**Comment by johanbrandhorst** [comment] 2016-11-07 09:23
@tamird even without the use of `gogo/protobuf` generated files? I hadn't seen it in our logs before we made the switch but as I mentioned I haven't yet taken a closer look.

**Comment by johanbrandhorst** [comment] 2016-11-11 15:00
I was able to reproduce the `proto: no coders for int` using the example provided by grpc-gateway, so I've raised https://github.com/grpc-ecosystem/grpc-gateway/issues/259 now. I think this can probably be closed unless there's anything else to add?

**Comment by awalterschulze** [comment] 2016-11-11 15:11
Good work

**Comment by awalterschulze** [comment] 2016-11-20 11:50
I guess since https://github.com/grpc-ecosystem/grpc-gateway/issues/259 is closed this issue can also be closed?

**Comment by johanbrandhorst** [comment] 2016-11-21 09:06
At least the `proto: no coders for int` message is fixed now. I think the original issue is probably slightly different but I wouldn't object to closing for now anyway as the cockroachdb workaround seems to work well.

**Comment by awalterschulze** [comment] 2016-11-21 19:19
@tamird This link is broken
For reference: https://github.com/cockroachdb/cockroach/blob/develop/util/jsonpb_marshal.go
Maybe someone still wants to bring an issue up with grpc-gateway about this interface?
Or maybe we could at least split out this code into a repo that others can use?

**Comment by tamird** [comment] 2016-11-21 19:21
Updated the link.

**Comment by johanbrandhorst** [comment] 2017-03-02 09:35
The underlying issue here has reared it's head again in enum parsing in the grpc-gateway. See https://github.com/grpc-ecosystem/grpc-gateway/issues/320. Again it is because gogo/protobuf RegisterEnum doesn't register against golang/protobuf and so when grpc-gateway attempts to map an enum it fails to find it.

**Comment by awalterschulze** [comment] 2017-03-02 09:49
Should we create a plugin to allow you to register with both gogoprotobuf and golang/protobuf or something like that.
I would personally like to create a plugin that does not import either, maybe these use cases can overlap?
Obviously not importing either will break extensions and ptypes.Any, but everything else should work if its implemented correctly.

**Comment by johanbrandhorst** [comment] 2017-03-02 09:57
I would like something like that for better cross-compatibility.

**Comment by awalterschulze** [comment] 2017-03-02 14:21
It would be useful for me (to try and to only build one new feature) if you could provide a repo which produces this problem, with an easy way for me to test.
Are you ok with no support for ptypes.Any and proto2 Extensions?

**Comment by johanbrandhorst** [comment] 2017-03-02 14:27
@awalterschulze Pinging you on the gopher slack for further discussion

**Comment by awalterschulze** [comment] 2017-03-02 14:31
Can we please keep the discussion here.

**Comment by johanbrandhorst** [comment] 2017-03-02 14:36
Okay, my org would have no problems with a plugin that doesn't support ptypes.Any or proto2 extensions. What kind of example are you interested in? The reason it's not working right now with the grpc-gateway is because it looks in a map created by `golang/proto.RegisterEnum` while all our generated files call `gogo/proto.RegisterEnum`

**Comment by awalterschulze** [comment] 2017-03-02 14:52
Why does it look at this map? Is it only for json marshaling?

**Comment by johanbrandhorst** [comment] 2017-03-02 14:53
@awalterschulze It looks at the map so that it can map from the enum string to the enum code and vice versa. It's to allow things like `https://my.com/api/v1/method?enum_variable=MY_ENUM_VALUE` to be translated into the correct enum numeric representation.

**Comment by johanbrandhorst** [comment] 2017-03-02 14:54
This is the relevant code: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/query.go#L150

**Comment by johanbrandhorst** [comment] 2017-03-02 16:08
As a side note, if this is at all unpleasant to consider, @mwitkow sed commands can be run post-generation to fix this issue, so it doesn't need to implemented at this level.

**Comment by awalterschulze** [comment] 2017-03-02 16:12
Ah ok, so grpc-gateway uses this in a totally different way.   Thats unfortunate.
That means it has to register with github.com/golang/protobuf and there is no way around it :(

**Comment by johanbrandhorst** [comment] 2017-03-02 16:13
Indeed

**Comment by awalterschulze** [comment] 2017-03-02 16:19
Ok so you need a plugin that registers messages, enums, etc with both golang/protobuf and gogo/protobuf.
Maybe lets make a new issue for this?

**Comment by johanbrandhorst** [comment] 2017-03-02 16:20
I'll get on it :smile:

**Closed** 2017-03-06 20:22 UTC
Labels: question
