### ISSUE TITLE
casttype for bytes

### ISSUE THREAD

**Issue by tamird** [gogo/protobuf#58] opened 2015-06-05 22:03 UTC
Using a custom type with the unmarshaler plugin results in code that does not compile. I've created a tiny repro here: https://github.com/tamird/gogoproto_customtype

**Comment by awalterschulze** [comment] 2015-06-06 06:54
You should use casttype instead of customtype.
This feature is available on the casttype branch

**Comment by tamird** [comment] 2015-06-06 07:10
Can casttype be made available before proto3?

**Comment by tamird** [comment] 2015-06-06 07:53
Also casttype doesn't work correctly - in proto2 syntax:
```
message RangeTreeNode {
  optional bytes left_key = 4 [(gogoproto.casttype) = "Key"];
}
```
In the generated code, `LeftKey` should be a pointer (because this thing is nullable) but it is not. Even the more explicit:
message RangeTreeNode {
  optional bytes left_key = 4 [(gogoproto.nullable) = true, (gogoproto.casttype) = "Key"];
}
```
yields a value type rather than a pointer.

**Comment by awalterschulze** [comment] 2015-06-06 08:41
casttype is not made for the bytes type.
"Changes the generated field type. It assumes that this type is castable to the original goprotobuf field type. It currently does not support byte slices, structs or enums."
- http://gogo.github.io/doc/

If you have this usecase, maybe I should add this feature.
I was a little afraid, because I was getting sleepy and was a little worried about the side effects of just casting to a type if that type does not imply a copy.

For bytes I still recommend customtype, but I could add this feature if you think it would be useful?

**Comment by awalterschulze** [comment] 2015-06-06 08:45
I am thinking about merging proto3 back into master before proto3 is officially released, but I don't know yet.
golang/protobuf does not have a problem with merging their proto3 support into their master branch, so I guess I should ask myself what I am afraid of.
I'll have to run some more tests first.

I think it would be really great to launch the gofast feature on the master branch.
Why would you want this feature in master asap?

**Comment by awalterschulze** [comment] 2015-06-06 09:01
Ok I ran some tests.  It all looks good.
I merged proto3 into master.

**Comment by awalterschulze** [comment] 2015-06-06 09:32
If I make casttype work for bytes as well.  Their is a problem in proto/text which is very easy to fix, but their is another problem in encoding/json

**Comment by awalterschulze** [comment] 2015-06-06 09:34
This issue is now a duplicate of https://github.com/gogo/protobuf/issues/36.

**Comment by awalterschulze** [comment] 2015-06-06 09:42
This is the issue with bytes as a casttype.
http://play.golang.org/p/RXlhj9_ld5

**Comment by awalterschulze** [comment] 2015-06-06 15:23
Do you have any ideas, maybe some annotation, that could fix this?

**Comment by tamird** [comment] 2015-06-06 16:29
I think in this case (our type is an alias for `[]byte`) we should use
casttype and the Marshal/Unmarshal/Size/whatever implementations should be
generated to cast to `[]byte` internally. What do you think?

**Comment by awalterschulze** [comment] 2015-06-07 09:59
How does that solve the json problem?

**Comment by tamird** [comment] 2015-06-07 20:23
http://play.golang.org/p/l9N7d3SPc0

**Comment by awalterschulze** [comment] 2015-06-08 08:24
Of course :)
Ok but it was not quite there

http://play.golang.org/p/Hpb0FEssL6

**Comment by awalterschulze** [comment] 2015-06-08 08:33
Ok the casttype branch should now support bytes as a casttype.

**Comment by awalterschulze** [comment] 2015-06-08 08:34
Please reopen this issue it the problem still occurs.

**Closed by awalterschulze** 2015-06-08 08:34 UTC
