### ISSUE TITLE
Merge ptypes from golang/goprotobuf

### ISSUE THREAD

**Issue by stevvooe** [gogo/protobuf#155] opened 2016-03-11 00:40 UTC
I am not sure what your policy on back-porting changes from goprotobuf, but it looks like `ptypes` has landed. Using these has been a pain point up until now.

https://github.com/golang/protobuf/commit/750c6bd0827ae5f3ebc8f49c6dedacc7c5f555b4

**Comment by awalterschulze** [comment] 2016-03-11 07:53
I would also like to merge it asap.
I pretty much to it manually for each of their commits.
I am just waiting for it to stabilise, because I think there is still some more discussion on the topic.

This is the last commit I have merged
https://github.com/golang/protobuf/commit/8cf720c393043e52c9da1e8c980e9bd4f89fa672
Which is a link I provide on gogo.github.io and it should also be quite verbose in the gogoprotobuf commit log.

I will prefer to do this one myself.
I also want to think through the problems of having the ptypes be standard go types like time.Time

**Comment by awalterschulze** [comment] 2016-03-11 14:13
I started updating gogoprotobuf a bit.
I am up to date to February again, but there is more work for me to do.

**Comment by stevvooe** [comment] 2016-03-11 23:56
@awalterschulze Great! No hurry here.

**Comment by awalterschulze** [comment] 2016-03-16 11:58
Wait for a fix for this issue below before I continue merging.
https://github.com/golang/protobuf/issues/148

**Comment by awalterschulze** [comment] 2016-03-17 10:12
Continuing the work here https://github.com/gogo/protobuf/tree/ptypes

**Comment by awalterschulze** [comment] 2016-03-17 10:13
Also waiting to resolve this issue
https://github.com/golang/protobuf/issues/149

**Comment by awalterschulze** [comment] 2016-04-11 09:18
Ok seems 149 is closed, because its a duplicate of https://github.com/golang/protobuf/issues/143

**Comment by mwmahlberg** [comment] 2016-06-17 10:47
@awalterschulze Could you give a quick overview on the status, what exactly is blocking and maybe even how one can be of help here? For a new application we would like to use proto3 (for timestamps) _and_ gogoprotobuf, but as of now it would be an either/or decision.

**Comment by awalterschulze** [comment] 2016-06-17 13:26
We are waiting for this issue
https://github.com/golang/protobuf/issues/143

**Comment by awalterschulze** [comment] 2016-06-17 13:27
Please don't think that I don't also find this situation frustrating.

**Comment by stevvooe** [comment] 2016-06-17 19:43
@awalterschulze It might be a good idea to move on without the lesser used WKTs. The upstream has duration, timestamp and a few others that are common. Any reason those can't be merged?

**Comment by mwmahlberg** [comment] 2016-06-18 10:59
@awalterschulze I am really sorry in case I was not sufficiently clear on that  – I was by no means implying that the gogo team was to blame in any way. But I have to make a technology decision, and time is running away a bit. I would agree with @stevvooe that adding more commonly known (and _needed_) types would be preferable to wait until upstream sorted it out. I know that this decision implies a lot (technical debts being the smallest problem). But personally (and admittedly being more than a bit selfish in that opinion) I think that approach is viable.

**Comment by awalterschulze** [comment] 2016-06-20 13:40
No don't worry you weren't offensive in any way :)

I am worried about imports and proto_paths gone mad.
So doing some of types is just as hard as doing all the types.

**Comment by awalterschulze** [comment] 2016-06-20 14:19
But I started looking at it again anyway
https://github.com/golang/protobuf/issues/196

**Comment by awalterschulze** [comment] 2016-08-21 09:30
golang/protobuf has closed
https://github.com/golang/protobuf/issues/143
I have opened
https://github.com/golang/protobuf/issues/218

I think what I would like to do is place all the well known type .proto files into ./protobuf/google/protobuf/ just like the descriptor.proto currently is and just like https://github.com/google/protobuf/tree/master/src/google/protobuf currently does.

Then I want to place the resulting generated .pb.go files somewhere in one folder in the gogoprotobuf project.  Almost like https://github.com/google/go-genproto/tree/master/protobuf but with all the .pb.go files and not just the ones that are missing from ptypes.

I think this is much cleaner and easier to use than the current golang/protobuf implementation, but that is my opinion, what are yours?

Also does anyone know why the googleapis folder must be so closely coupled with the well known types, as they are here https://github.com/google/go-genproto
Why do they need to be in the same project?
I would really like to avoid this.

Also I will be adding two new extensions for timestamp and duration to allow the user to rather generate the fieldtype as the native time.Time and time.Duration.

Any objections or comments would be appreciated before I start this work.

@tamird @smarterclayton @stevvooe @mwmahlberg @mwitkow @chancez @gpaul @jdevilliers

**Comment by mwmahlberg** [comment] 2016-08-21 09:38
Hm, putting them into a different location would remove the "drop-in-replacement" capabilities, right? Not that this would be much of concern for me, but I guess that needs to be considered carefully. I'd assume the usual way of adopting gogo is "Hey, golang/protobuf does not provide <feature of gogo>. Is there an alternative implementation?" The more code changes the migration to gogo requires, the less likely it is going to happen, I guess.

**Comment by awalterschulze** [comment] 2016-08-21 11:17
Well I think you simply change you protoc command to import the descriptor path, which the new user already has to do, because of gogoproto which imports the descriptor.  The new generated code will now import the gogoprotobuf .pb.go files.  I don't think there is more code that needs to change, but maybe I am missing something?

**Comment by stevvooe** [comment] 2016-08-22 15:57
@awalterschulze The main issue with importing protobufs from other projects is the resolution of the import paths. We have lots of [import path mapping](https://github.com/docker/swarmkit/blob/master/api/gen.go) splayed throughout the project, even for our own protobufs.

I think the right approach is to reduce the complexity of import path mapping. Any solution that will allow use get rid of our [our ptype forks](https://github.com/docker/swarmkit/tree/master/api/duration), without complicating the build process, will meet our needs.

(note that we also have extra plugins that make this more challenging)

**Comment by awalterschulze** [comment] 2016-08-24 20:02
I have started some work here
https://github.com/gogo/protobuf/tree/wkt
In these two commits
https://github.com/gogo/protobuf/commit/55175811c0681a6fa7a50524481a139ab189633f
https://github.com/gogo/protobuf/commit/17944a13edf05cbfa59c3333e5344aece55c5d62

I still have to do lots of work, first of which will be using these in another struct and checking whether I have to do any import rewrites, because that is not what I want.  I'd rather use gogoreplace to change my version of the go_package, because then this only needs to happen once.

**Comment by awalterschulze** [comment] 2016-08-27 14:46
Ok this is not easy to do without the import mapping (-M parameter).

**Comment by awalterschulze** [comment] 2016-08-27 16:40
Here is the first attempt at using well known types
https://github.com/gogo/protobuf/tree/wkt/test/types
This still uses the -M parameter unfortunately.
I am struggling to see a way to do it without it.
I can obviously build something into protoc-gen-gogo to do this, but maybe some of you have some other ideas?

**Comment by awalterschulze** [comment] 2016-08-28 16:57
This branch is starting to become usable.
Feedback will be appreciated.

TODOs:

  * The -M parameter is still a problem that I don't know how to fix and could stay in the final solution if someone doesn't have a suggestion, because its definitely not worse than the golang/protobuf solution.
  * The NewPopulatedStruct for the struct.proto is generating structures which aren't valid for jsonpb.  Requires some investigation.
  * I am currently working on: gogoproto.stdtime and gogoproto.stdduration to generate time.Time and time.Duration field types instead of types.Timestamp and types.Duration.

**Comment by stevvooe** [comment] 2016-08-29 21:18
👍 

>The -M parameter is still a problem that I don't know how to fix and could stay in the final solution if someone doesn't have a suggestion, because its definitely not worse than the golang/protobuf solution.

I don't see this as a must have. Right now, our types are forked. I'm not sure if we can address all the issues, but we'd like to mitigate this risk.

> I am currently working on: gogoproto.stdtime and gogoproto.stdduration to generate time.Time and time.Duration field types instead of types.Timestamp and types.Duration. This work is happening on the std branch.

This would be ideal, as long as they are wire compatible with the google types (or there is a way to control whether they are uint/compound).

**Comment by awalterschulze** [comment] 2016-08-30 12:20
What do you mean with unit/compound?

**Comment by stevvooe** [comment] 2016-09-01 01:56
@awalterschulze There are two ways to represent timestamps/durations in protobuf. One is to have an integer mapping to nanoseconds or a unix timestamp. I've dubbed this "unit". The other is to follow the Timestamp/Duration types from the WKTs, which I've dubbed "compound".

In general, it would be nice to be able to work with `time.Duration`/`time.Time` types regardless of what legacy mapping was applied to that field. For example, if we have a field `foo_ms`, it would be  great to have that field be generation as a `time.Duration`, then have the package do the correct conversion to ms.

**Comment by awalterschulze** [comment] 2016-09-02 18:13
This would then require gogoproto.stdtime to be of type string and this would then require the user to map to a marshal and unmarshal function, but this can become quite verbose.

Or we can only implement a few standard functions.
I can imagine legacy timestamp structs, int64 nanoseconds, uint64 nanoseconds, int64 milliseconds, int64 seconds.
There are quite a few legacy options.

The choice of what to implement and what not to implement can become quite contentious.

**Comment by stevvooe** [comment] 2016-09-02 22:55
> This would then require gogoproto.stdtime to be of type string and this would then require the user to map to a marshal and unmarshal function, but this can become quite verbose.

You can define structures to accept into the plugin. We did this for our [authenticated wrapper plugin](https://github.com/docker/swarmkit/blob/master/protobuf/plugin/plugin.proto#L11`).

Something like this maybe

```proto
message Something {
  google.protobuf.Timestamp timestamp [(gogoproto.stdtime) = {enabled: true}]; // shouldn't have to, but this should generate a time.Time field
  uint64 my_legacy_field_ms [(gogoproto.stdtime) = {enabled: true units: "ms"}]; // generate time.Time and convert from milliseconds
}
```

Maybe I'm off in the weeds here...

**Comment by awalterschulze** [comment] 2016-09-03 08:05
Ok so this way all legacy numbers (units) are supported, but not legacy messages.
On the positive this is probably at least 90% of cases and supporting legacy messages is a lot more effort.
This is assuming we ignore timezones, which I think is a good idea.
If only numbers, timestamp and duration are supported then the type gives us a lot of information the only other information we need is the time unit.
I hope to get away without a structure extension.

Here is my new proposal
Phase one:
```
gogoproto.stdtime=true  // only for timestamp
gogoproto.stdduration=true // only for duration
```

Phase two: approved by me, but maybe not implemented by me?
```
gogoproto.timeunit="ns" // or "s" or "ms" only for int64, uint64, sfixed64, fixed64, sint64
gogoproto.durationunit="ns" // or "s" or "ms" only for int64, uint64, sfixed64, fixed64, sint64
```

What do you think?

**Comment by awalterschulze** [comment] 2016-09-03 12:07
The `struct` and `any` issues I am having are still issues in the main golang/protobuf library as well
https://github.com/golang/protobuf/pull/208
https://github.com/golang/protobuf/issues/216

**Comment by awalterschulze** [comment] 2016-09-04 12:19
The `wkt` branch is done.   It includes the well known types (ptypes).

Generating fields of type time.Time and time.Duration instead of google_protobuf.Timestamp and google_protobuf.Duration is not included in the `wkt` branch.  This development is happening on the `std` branch and this progress will be tracked here https://github.com/gogo/protobuf/issues/196

I plan to merge the `wkt` branch next weekend ( 10 September )
If you have any objections or ideas on how to better this implementation.  Now is the time.
@tamird @smarterclayton @stevvooe @mwmahlberg @mwitkow @chancez @jdevilliers

**Comment by awalterschulze** [comment] 2016-09-10 08:23
I have merged the wkt branch
The jsonpb bug with Any and Struct can be tracked here
https://github.com/gogo/protobuf/issues/197

**Closed by awalterschulze** 2016-09-10 08:23 UTC
Labels: bug
